id: "vllm"
tests:
  # This log sample satisfies the validation.
 -
  sample: |-
    INFO 06-11-2024 21:02:01 cpu_executor.py:72] # CPU blocks: 7281
  result:
    custom:
      level: "INFO"
      timestamp: 1718139721000
      logger:
        lineno: 72
        name: "cpu_executor.py"
    message: '# CPU blocks: 7281'
    status: "info"
    tags:
     - "source:LOGS_SOURCE"
    timestamp: 1718139721000
# Log entries in the wild don't include a year in their timestamp. This confuses the test framework.
# Sample disabled until we address this.
#  -
#   sample: |-
#     WARNING 06-11 21:01:50 ray_utils.py:46] Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For multi-node inference, please install Ray with `pip install ray`.
#   result:
#     custom:
#       level: "WARNING"
#       timestamp: 1718132510
#       logger:
#         lineno: 46
#         name: "ray_utils.py"
#     message: |-
#       Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For multi-node inference, please install Ray with `pip install ray`.
#     status: "warning"
#     tags:
#      - "source:LOGS_SOURCE"
#     timestamp: 1718132510
